allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': true
  '@whiskeysockets/baileys': false
  prisma: false
  protobufjs: false

overrides:
  brace-expansion: '>=1.1.16'
  fast-uri: '>=3.1.4'
